### PR TITLE
Add webpack dep to match prod archetype.

### LINKED ISSUE #1: Need webpack peerDependency to track prod archetype.
See: https://github.com/FormidableLabs/victory/issues/536

Basically `webpack-dev-server` can pick up other `webpack`s if we don't lock down one earlier.

### PR DESCRIPTION
**Pull request by ryan-roemer**
Fixes #1 
Fixes FormidableLabs/victory#536

/cc @boygirl @GreenGremlin

### CODE REVIEW

**Comment by boygirl** [comment]
@ryan-roemer LGTM. Should I patch just this repo, or do you want to keep it in version lockstep with `builder-victory-component`?

**Comment by ryan-roemer** [comment]
I think do both ? Or we could just do dev and bump both together or leapfrog going forward...

Also, first I'm getting:

```
ERROR in multi app
Module not found: Error: Cannot resolve module 'webpack/hot/dev-server' in /Users/rye/scm/fmd/victory
 @ multi app
webpack: Failed to compile.
```

And looking into that. That lib _is_ there.

Do you know of any current issues with our hot demo configs?

**Comment by boygirl** [comment]
None that I know of, but I almost always run without hot reloading.

**Comment by ryan-roemer** [comment]
You now, our hot reload setup IIRC is super out of date and obsolete. Should se just maybe look to remove?

IIRC I think it wasn't working before?

**Comment by boygirl** [comment]
I'm fine with removing it. I will PR the other repos to switch `npm start` to `builder run dev`

**Comment by boygirl** [comment]
Good to merge this PR for now, though? This is still necessary for preventing potential conflicting webpacks, yes?

**Pull request merged**
